source 'https://rubygems.org'

gem 'jekyll', '~>3.4'

group :jekyll_plugins do
	gem 'jekyll-archives', '~>2.1'
	gem 'jekyll-sitemap', '~>1.0'
	gem 'jekyll-seo-tag', '~>2.1'
	gem 'jekyll-feed', '~>0.9'
	gem 'jekyll-extract-element', '~>0.0'
	gem 'jekyll-asciinema', '~>0.2'
end
